project:
  type: website
  output-dir: docs

website:
  title: "Pete Pritchard"
  favicon: /assets/favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
  google-analytics: 
    tracking-id: "G-TLBL8KD48W" 
  
  page-footer: 
    background: light
    left: © Copyright 2024, Pete Pritchard
    right: This website is built with {{< fa heart title="a heart" >}}

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: "_includes/google-analytics.html"
    markdown:
      extensions: [shortcodes]



