project:
  type: website
  output-dir: docs

website:
  title: "Pete Pritchard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects 
  
  page-footer: 
    background: light
    left: © Copyright 2024, Pete Pritchard
    right: This website is built with {{< fa heart title="a heart" >}}

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    markdown:
      extensions: [shortcodes]




