---
title: "CV"
css: styles.css
---

# Contact Information

- **Name:** Pete Pritchard
- **Email:** petep at umich dot edu
- **Phone:** (423) eight hundred-1887

------

<a href="assets/petePritchardResume.pdf" class="btn btn-primary" download="petePritchardResume.pdf">Download Resume</a>

# Experience

### Student Researcher, NASA
**Ann Arbor, MI** | *January 2025 - May 2025*

- Enhanced performance of NASA’s Sequential Monte Carlo Sampler library by developing new features with JAX and BlackJax, rewriting outdated code, and implementing gradient-accelerated forward kernels suited for high-performance computing clusters, significantly improving computational efficiency
- Improved code maintainability and reliability through robust documentation, benchmarking, and comprehensive unit testing, ensuring seamless deployment on NASA’s high-performance computing infrastructure

### Data Science Intern, NASA
**Mountainview, CA** | *June 2024 – August 2024*

- Used Python to build real-time data applications of operational and test data to provide comprehensive visualizations, reveal patterns and drive more effective decision-making and business outcomes, emphasizing critical insights such as cost and performance metrics
- Developed real-time analytics dashboard processing 1TB+ of operational data daily
- Engineered automated scheduling system that reduced resource allocation time from 4 hours to 15 minutes, adopted by
20+ engineers across 5 departments

### Data Science Intern, NASA
**Washington, DC** | *June 2023 – August 2023*

- Developed and deployed short-term and long-horizon demand forecast models and dashboard using Python and Dash, enhancing forecasting accuracy and decision-making
- Created API wrapper reducing report generation time by 90%, saving 400+ hours annually across management team
- Optimized database by enacting 50+ SQL queries, reducing average query time by 75% and handling 100+ daily requests
- Contributed to database redesign that improved retrieval efficiency by 60% and reduced storage requirements by 40%

### Graduate Student Instructor, University of Michigan
**Ann Arbor, MI** | *August 2023 – Present*

- Awarded the Outstanding Graduate Student Instructor Team Award by the Statistics Department
- Lead instructor for 4 lab sections with 100+ total students, maintaining very high average student satisfaction rating
- Promoted to Graduate Student Mentor after one semester, supervised a team of 7 teaching assistants

### Research Assistant, University of Tennessee
**Chattanooga, TN** | *Junuary 2023 – May 2023*

- Surveyed statistical and ML methods to predict the spread of viruses using Google Trends and Covid-19 data
- Developed an LSTM deep learning networks model with the use of R (Keras, Tensorflow)
- Achieved higher model performances compared with classic time series approaches (VAR, ARIMA)
- Presented findings at UT, Chattanooga’s research dialogue conference

### Research Assistant, University of Tennessee
**Chattanooga, TN** | *August 2022 – January 2023*

- Assisted a project that formulated a new mixed-integer linear model to optimally locate Emergency Medical Service vehicle facilities to decrease response time, and ultimately save lives
- My contributions included data assembly, running and analyzing tests on GPU clusters, and writing the report
- The solution resulted in a 12.38 – 22.02 percent increase in overall coverage

### Data Analytics Intern, Stray Dog Designs
**Chattanooga, TN** | *May 2020 – August 2020*

- Analyzed campaign performance metrics to enhance social media marketing efforts
- Created custom dashboards and automated weekly reports with Google Analytics and Data Studio
- Developed marketing mix models and clustering algorithms for customer segmentation to boost ROA

------

# Education

### MS, Applied Statistics
**University of Michigan, Ann Arbor** | *Month Year – Month Year*

- Coursework: Regression, Probability Theory, Statistical Inference, Multivariate Analysis, Machine Learning, Time Series Analysis, Statistical Computing, Bayesian Modeling, Design of Experiments

### BS, Applied Mathematics & Economics
**University of Tennessee, Chattanooga** | *August 2020 – May 2023*

------

# Skills

- **Languages:** Python, R, SQL, C++
- **Developer Tools:** Git, Google Cloud Platform, Dataiku, Docker, Looker, Linux/Unix, Dash, LaTeX, Jupyter Notebooks, Emacs
- **Libraries:** Pandas, NumPy, PyTorch, SciPy, Jax, BlackJax, PyMC, Scikit-learn, Matplotlib, Seaborn, Ggplot2, RStan, RCpp
- **Modeling:** Supervised Learning, Neural Networks, Clustering, Time Series, Hidden Markov Process, Monte Carlo Methods
- **Soft Skills:** Spanish (Working level), Communication, Leadership

------

# Awards and Honors 

### Outstanding Graduate Student Instructor Team Award
**University of Michigan, Ann Arbor** | *May 2025*

### John C. Stophel Distinguished Student Award
**University of Tennesee, Chattanooga** | *December 2022*

- The John C. Stophel Distinguished Student Award is presented annually to recognize high potential business students who have made significant and meaningful contributions to UTC, the Gary W. Rollins College of Business and their communities while maintaining a strong academic record.The John C. Stophel Distinguished Student Award is presented annually to recognize high potential business students who have made significant and meaningful contributions to UTC, the Gary W. Rollins College of Business and their communities while maintaining a strong academic record.



### Ziad Keilany Scholarship in Economics
**University of Tennesee, Chattanooga** | *December 2022*


### Joe & Rachael Decosimo Scholarship
**University of Tennesee, Chattanooga** | *December 2022*

------

# References

Available upon request.



